---
title: "Rotifer response to temperature"
author: "Alex Mendelson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(growthrates)
library(lme4)
library(car)
library(performance)

```

## Data import and factoring

```{r dataImport, include = TRUE}
data <- read.csv("../data/tempRes2.csv")

data$cloneID <- paste(data$Site, data$Leaf, data$Clone, sep="-")

data$Site <- as.factor(data$Site)
data$Leaf <- as.factor(data$Leaf)
data$Treatment <- as.factor(data$Treatment)
data$Clone <- as.factor(data$Clone)
data$cloneID <- as.factor(data$cloneID)
```

## Growth curves

```{r growthCurveData, echo = FALSE}
cloneAvg <- data %>%
  group_by(Day, Treatment, Site, cloneID) %>%
  summarise(
    avgCount = mean(Count),
    SE = sd(Count) / sqrt(n())
  )
```

```{r growthCurveCombined}
# avg counts all clones one plot

ggplot(cloneAvg, aes(x = Day, y = avgCount, color = Treatment, group = interaction(cloneID, Treatment, Site))) +
  geom_point() +
  geom_line() +
  labs(y = "Rotifer Abundance", x = "Day", caption = "Figure 1. Average counts over time in 2 temps, pooled clones") +
  scale_x_continuous(breaks = seq(3, 24, by = 3)) +
  scale_color_manual(values = c("25C" = "blue", "30C" = "red")) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),            
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8),  
    strip.background = element_rect(fill = "gray90", color = NA), 
    plot.caption = element_text(hjust = 0)  
  )
```

```{r growthCurveIndiv}
# avg counts (+/- SE) over time in 2 temps (color) wrapped by cloneID

ggplot(cloneAvg, aes(x = Day, y = avgCount, color = Treatment, group = interaction(cloneID, Treatment, Site))) +
  geom_point() +
  geom_line() +
  labs(y = "Rotifer Abundance", x = "Day", caption = "Figure 2. Average counts (+/- SE) over time in 2 temps (color) wrapped by cloneID") +
  scale_x_continuous(breaks = seq(3, 24, by = 3)) +
  scale_color_manual(values = c("25C" = "blue", "30C" = "red")) +
  geom_errorbar(aes(ymin = avgCount - SE, ymax = avgCount + SE), width = 0.2, alpha = 0.6) +
  theme_minimal() +
  facet_wrap(~cloneID) +
  theme(
    panel.grid = element_blank(),            
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8),  
    strip.background = element_rect(fill = "gray90", color = NA), 
    plot.caption = element_text(hjust = 0)  
  )

```

## Growth rates

Folllowing this tutorial:
https://cran.r-project.org/web/packages/growthrates/vignettes/Introduction.html

```{r grothRatesData}

rateData <- data.frame(
  site = data$Site,
  leaf = data$Leaf,
  clone = data$Clone,
  replicate = data$ID,
  time = data$Day,
  count = data$Count
)

rateData <- rateData %>%
  mutate(
    replicate = as.integer(substr(replicate, nchar(replicate), nchar(replicate))),
    count1 = count + 1
  )
```

```{r rateTesting}
# splitting data up
splitData <- multisplit(rateData, c("site", "leaf", "clone", "replicate"))

# Testing with single data sets with the 'Easy Linear Method', adapted from Hall et al. 2014:

# separate out only one replicate (site C, leaf 1, clone 1, rep 1)
dat <- splitData[[1]]

fit <- fit_easylinear(dat$time, dat$count +1)

summary(fit)

coef(fit) # exponential growth parameters

plot(fit, log = "y") # log-transformed data used in 'fit'
plot(fit) # re-transformed to original

# nonparametric smoothing splines for MAX GROWTH
dat <- splitData[[1]]
time <- dat$time
y <- dat$count +1

res <- fit_spline(time, y)


plot(res, log = "y")
plot(res)
```

```{r fullRateEstimates}
# easy linear for ALL replicates

manyEasyFits <- all_easylinear(count1 ~ time | site + leaf + clone + replicate, data = rateData)

# fit model results built into data frame
# Assigned new treatment column based on replicate #

easyFitResults <- as.data.frame(coef(manyEasyFits))

easyFitResults <- easyFitResults %>%
    rownames_to_column(var = "id") %>%
    separate(id, into = c("site", "leaf", "clone", "replicate"), sep = ":", convert = TRUE) %>%
    mutate(
      treatment = case_when(
        replicate %in% c(1, 2, 3) ~ "low",
        replicate %in% c(4, 5, 6) ~ "high"
      )
    )

# plot first 8 easyFit models for low and high treatment 

plot_indices <- c(1:8, 52:59)

par(mfrow = c(4,4), mar = c(2,2,2,1))
for (i in plot_indices) {
  plot(manyEasyFits[[i]])
  this_mumax <- round(easyFitResults$mumax[i], 4)
  this_treatment <- easyFitResults$treatment[i]
  mtext(paste("mumax:", this_mumax), side = 3, adj = 0, line = -1, cex = 0.8)
  title(main = paste("Treatment:", this_treatment), cex.main = 1)
}


```

```{r mumaxComparison}
# mumax (maximum growth rate) values by treatment

rateAvgPlot <- easyFitResults %>%
  group_by(treatment) %>%
  summarise(
    mean = mean(mumax),
    SE = sd(mumax) / sqrt(n()),
    site = site
  )

ggplot(rateAvgPlot, aes(x = treatment, y = mean, fill = treatment)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.5) +
  geom_errorbar(aes(ymin = mean - SE, ymax = mean + SE), width = 0.35) +
  ylab("Maximum growth rate (mumax)") +
  xlab("Temperature treatment") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),            
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8),  
    strip.background = element_rect(fill = "gray90", color = NA), 
    plot.caption = element_text(hjust = 0),
    legend.position = "none"
  )

rateAvgSite <- easyFitResults %>%
  group_by(treatment, site) %>%
  summarise(
    mean = mean(mumax),
    SE = sd(mumax) / sqrt(n()),
    .groups = "drop"
  )

ggplot(rateAvgSite, aes(x = treatment, y = mean, fill = site)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.6), width = 0.5) +
  geom_errorbar(aes(ymin = mean - SE, ymax = mean + SE),
                position = position_dodge(width = 0.6), width = 0.25) +
  ylab("Maximum growth rate (μmax)") +
  xlab("Temperature treatment") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8),
    strip.background = element_rect(fill = "gray90", color = NA),
    plot.caption = element_text(hjust = 0)
  )

rateAvgSite <- easyFitResults %>%
  group_by(site) %>%
  summarise(
    mean = mean(mumax),
    SE = sd(mumax) / sqrt(n()),
    .groups = "drop"
  )

ggplot(rateAvgSite, aes(x = site, y = mean, fill = site)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_errorbar(aes(ymin = mean - SE, ymax = mean + SE), width = 0.25) +
  ylab("Maximum growth rate (μmax)") +
  xlab("Site") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8),
    strip.background = element_rect(fill = "gray90", color = NA),
    plot.caption = element_text(hjust = 0),
    legend.position = "none"
  )

```

```{r lmer}

easyFitResults$site <- as.factor(easyFitResults$site)
easyFitResults$leaf <- as.factor(easyFitResults$leaf)
easyFitResults$clone <- as.factor(easyFitResults$clone)
easyFitResults$replicate <- as.factor(easyFitResults$replicate)
easyFitResults$treatment <- as.factor(easyFitResults$treatment)

model1 <- lmer(mumax ~ treatment + (1|site) + (1|leaf) + (1|clone), data = easyFitResults)

plot(model1)

qqnorm(residuals(model1))
qqline(residuals(model1))

summary(model1)

varcomps <- VarCorr(model1)
print(varcomps, comp = "Variance", digits = 22)

Anova(model1)

# nested

model2 <- lmer(mumax ~ treatment + (1|site) + (1|site:leaf) + (1|site:leaf:clone), data = easyFitResults)

summary(model2)

# nested steve style

model3 <- lmer(mumax ~ treatment + (1|site) + (1|leaf) + (1|clone) + (1|site:leaf) + (1|leaf:clone) +(1|site:clone) + (1|site:leaf:clone), data = easyFitResults)

summary(model3)
```

# Test with some fake data. Counts in Pleaphase site 1.5x

```{r highVarTest}

fakeData <- read.csv("../data/tempRes2_highSiteVariance.csv")

fakeData$cloneID <- paste(fakeData$Site, fakeData$Leaf, fakeData$Clone, sep="-")

fakeData$Site <- as.factor(fakeData$Site)
fakeData$Leaf <- as.factor(fakeData$Leaf)
fakeData$Treatment <- as.factor(fakeData$Treatment)
fakeData$Clone <- as.factor(fakeData$Clone)
fakeData$cloneID <- as.factor(fakeData$cloneID)

fakeRateData <- data.frame(
  site = fakeData$Site,
  leaf = fakeData$Leaf,
  clone = fakeData$Clone,
  replicate = fakeData$ID,
  time = fakeData$Day,
  count = fakeData$Count
)

fakeRateData <- fakeRateData %>%
  mutate(
    replicate = as.integer(substr(replicate, nchar(replicate), nchar(replicate))),
    count1 = count + 1
  )

fakeManyEasyFits <- all_easylinear(count1 ~ time | site + leaf + clone + replicate, data = fakeRateData)

# fit model results built into data frame
# Assigned new treatment column based on replicate #

fakeEasyFitResults <- as.data.frame(coef(fakeManyEasyFits))

fakeEasyFitResults <- fakeEasyFitResults %>%
    rownames_to_column(var = "id") %>%
    separate(id, into = c("site", "leaf", "clone", "replicate"), sep = ":", convert = TRUE) %>%
    mutate(
      treatment = case_when(
        replicate %in% c(1, 2, 3) ~ "low",
        replicate %in% c(4, 5, 6) ~ "high"
      )
    )

fakeModel1 <- lmer(mumax ~ treatment + (1|site) + (1|leaf) + (1|clone), data = fakeEasyFitResults)

summary(fakeModel1)
```

# LRT & ICC (with real data)
Prereq: chunk8 - fullRateEstimates

```{r LRT & ICC}

model1_full <- lmer(mumax ~ treatment + (1|site) + (1|leaf) + (1|clone), data = easyFitResults)

model1_reduced <- lmer(mumax ~ treatment + (1|leaf) + (1|clone), data = easyFitResults)

# LRT:
anova(model1_full, model1_reduced)
# p = 1; remove site

icc(model1_reduced)

ggplot(easyFitResults, aes(x = site, y = mumax)) +
  geom_boxplot(fill = "lightblue") +
  geom_jitter(width = 0.1, alpha = 0.5) +
  ylab("Maximum Growth Rate (μmax)") +
  xlab("Site") +
  theme_minimal()

```

```{r explicitNesting}

model4 <- lmer(mumax ~ treatment + (1|site/leaf/clone), data = easyFitResults)
summary(model4)
plot(model4)
qqp(resid(model4))
```